env:
  AZURE_WEBAPP_NAME: your-app-name    # Deporteseuropeos
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # https://github.com/Snapdragon845GMS/Deporteseuropeos
  JAVA_VERSION: '1.8'                # 1.8
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}     #
